version: '3'

services:
  # Cassandra Image
  cassandra:
      image: cassandra:4.1.3
      container_name: cassandra
      hostname: cassandra
      ports:
        - "9042:9042"
      volumes:
        - "./cassandra/dockerdata:/var/lib/cassandra"
  
  # # Flink Image
  # jobmanager:
  #   image: flink:1.18
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager    
  #   volumes:
  #     - "C:/Self_Exploration/ChartDataPipeline/data:/opt/flink/data"

  # taskmanager:
  #   image: flink:1.18
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   scale: 1
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       taskmanager.numberOfTaskSlots: 2    
  #   volumes:
  #     - "C:/Self_Exploration/ChartDataPipeline/data:/opt/flink/data"

networks:
  market_data:
    driver: bridge