version: '3'

services:
  # Cassandra Image
  cassandra:
      image: cassandra:4.1.3
      container_name: cassandra
      hostname: cassandra
      ports:
        - "9042:9042"
      volumes:
        - "./cassandra/dockerdata:/var/lib/cassandra"
        - "./cassandra/scripts:/docker-entrypoint-initdb.d"

  # Kafka Image
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

 # Flink Image
  jobmanager:
    image: flink:1.18
    ports:
     - "8081:8081"
    command: jobmanager
    environment:
     - |
       FLINK_PROPERTIES=
       jobmanager.rpc.address: jobmanager
    volumes:
     - "./data:/opt/flink/data"

  taskmanager:
   image: flink:1.18
   depends_on:
     - jobmanager
   command: taskmanager
   environment:
     - |
       FLINK_PROPERTIES=
       jobmanager.rpc.address: jobmanager
       taskmanager.numberOfTaskSlots: 2
   volumes:
     - "./data:/opt/flink/data"

  # Python Script Image
  script:
    build:
      context: ./dockerfiles
      dockerfile: python_script.Dockerfile
    image: python_script
    depends_on:
      - kafka
    volumes:
     - "./python_script:/usr/app/src"

networks:
  market_data:
    driver: bridge